### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by chadmckell** [joeyhook/moog-filter-plugin#1]
Hey Joey-

Nice work. The algorithms in the zipped JUCE projects look really good. However, something goes wrong during build time (for both linear and nonlinear models). For example, Xcode flagged the SliderListener class in the "GenericEditor.h" file as "expected class name". I'm not sure what that means exactly, but it caused the builds to fail. Maybe I'm missing a required library. Do you also see this error when you try to run the code? 

These are nifty implementations by the way. I'm interested to know what rMod and w0Mod do. Did we talk about that in PBMMI?

Chad

**Comment by mhamilt** [comment]
It looks like it was just the JUCE libraries not being linked. Hopefully the JUCE example project should clear up the ambiguity

[currently here](https://github.com/joeyhook/moog-filter-plugin/tree/master/recent/JUCEMoogVCFPlugInExample)
